// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file is generated by crypto/internal/backend. DO NOT EDIT. DO NOT manually create files with the prefix "backenderr_gen_".

//go:build goexperiment.opensslcrypto && !(goexperiment.opensslcrypto && linux && cgo) && !goexperiment.allowcryptofallback

package runtime

func init() {
	`
	The goexperiment.opensslcrypto tag is specified, but other tags required to enable that backend were not met.
	Required build tags:
	  goexperiment.opensslcrypto && linux && cgo
	Please check your build environment and build command for a reason one or more of these tags weren't specified.
	
	If you only performed a Go toolset upgrade and didn't expect this error, your code was likely depending on fallback to Go standard library crypto.
	As of Go 1.21, Go crypto fallback is a build error. This helps prevent accidental fallback.
	Removing opensslcrypto will restore pre-1.21 behavior by intentionally using Go standard library crypto.
	
	For more information, visit https://github.com/microsoft/go/tree/microsoft/main/eng/doc/fips
	`
}
