// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file is generated by crypto/internal/backend. DO NOT EDIT. DO NOT manually create files with the prefix "backenderr_gen_".

//go:build goexperiment.boringcrypto && goexperiment.opensslcrypto

package runtime

func init() {
	`
	The boring and openssl backends are both enabled, but they are mutually exclusive.
	Please make sure only one crypto backend experiment is enabled by GOEXPERIMENT or '-tags'.
	For more information, visit https://github.com/microsoft/go/tree/microsoft/main/eng/doc/fips
	`
}
