// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file is generated by crypto/internal/backend. DO NOT EDIT. DO NOT manually create files with the prefix "backenderr_gen_".

//go:build goexperiment.systemcrypto && !goexperiment.boringcrypto && !goexperiment.cngcrypto && !goexperiment.opensslcrypto

package runtime

func init() {
	`
	The systemcrypto feature is enabled, but it was unable to enable an appropriate crypto backend for the target GOOS.
	For more information, visit https://github.com/microsoft/go/tree/microsoft/main/eng/doc/fips
	`
}
