// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.xcryptobackendswap
// +build !goexperiment.xcryptobackendswap

package goexperiment

const XCryptoBackendSwap = false
const XCryptoBackendSwapInt = 0
