// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.opensslcrypto
// +build !goexperiment.opensslcrypto

package goexperiment

const OpenSSLCrypto = false
const OpenSSLCryptoInt = 0
