// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.allowcryptofallback
// +build goexperiment.allowcryptofallback

package goexperiment

const AllowCryptoFallback = true
const AllowCryptoFallbackInt = 1
