// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.allowcryptofallback
// +build !goexperiment.allowcryptofallback

package goexperiment

const AllowCryptoFallback = false
const AllowCryptoFallbackInt = 0
